[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "graph-platform"
version = "0.1.0"
description = "Platform core orchestrating graph plugins"
requires-python = ">=3.11"
dependencies = [
    "graph-api"
]

[tool.setuptools.packages.find]
where = ["."]

[tool.setuptools.package-data]
graph_platform = [
    "django_app/templates/platform_django/*.html",
    "django_app/static/platform_django/js/*.js",
    "flask_app/templates/platform_flask/*.html",
]
